# Generated by Django 5.2 on 2025-04-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='productimage',
            new_name='productImage',
        ),
    ]
